name: color_simulator
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: 2.2.0
  freezed_annotation: 2.2.0
  gap: 2.0.1
  go_router: 6.0.9
  http: 0.13.5
  meta: 1.8.0
  simple_logger: 1.9.0+2
  intl: 0.18.0
  image_picker: 0.8.6+2
  image_picker_for_web: 2.1.10
  riverpod_annotation: 2.6.1
  flutter_colorpicker: 1.0.3
  image: 4.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: 2.3.3
  freezed: 2.3.2
  go_router_builder: 1.1.0
  json_serializable: 6.6.1
  riverpod_generator: 1.2.0


flutter:
  uses-material-design: true
  assets:
    - assets/test.png